name: Build and deploy Vite app to Azure Web App - ejemplo-react

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install and build
        run: |
          npm install
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: vite-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: vite-app

      - name: Move build files to root
        run: |
          shopt -s dotglob
          mv vite-app/* .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_81A208E6D2224FFA9EEF45CB17A75F98 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D122DF29D14F40E6A9BF2EF72D8A3CB8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A229F764CA5E4A4FAF705E4A29BB481B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ejemplo-react'
          slot-name: 'Production'
          package: .
